spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongodb:27017/lms_emi?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
