spring:
  datasource:
    url: jdbc:mysql://mysql:3306/lms_identity?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

app:
  seed:
    root-admin:
      email: ${ROOT_ADMIN_EMAIL}
      password: ${ROOT_ADMIN_PASSWORD}
