spring:
  datasource:
    url: jdbc:mysql://mysql:3306/lms_identity?createDatabaseIfNotExist=true
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
